[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "ComingStudio"
name = "Yaju_Mandrake"
description = "Replaces Mandrake screaming with the Yaju Senpai."
websiteUrl = "https://github.com/wellcoming/PEAK-YajuMandrake"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
loaforc-loaforcsSoundAPI = "2.0.8"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/YajuMandrake/release/com.github.wellcoming.YajuMandrake.dll"
target = "plugins/"

[[build.copy]]
source = "../../artifacts/bin/YajuMandrake/release/YajuMandrake"
target = "plugins/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = ["peak"]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = ["mods"]
